# Generated by Django 4.2.16 on 2026-03-25 13:58

from django.db import migrations, models
import host_mgr.base_models
import host_mgr.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.CharField(default=host_mgr.base_models.uuid_hex_str, editable=False, max_length=32, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('extra', host_mgr.fields.NullableJSONStringField(blank=True, default=None, null=True, verbose_name='扩展字段')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='城市名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '城市',
                'verbose_name_plural': '城市',
                'db_table': 'city',
                'ordering': ['id'],
            },
        ),
    ]
