# Generated by Django 4.2.16 on 2026-03-25 09:25

from django.db import migrations, models
import host_mgr.base_models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_alter_city_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.CharField(default=host_mgr.base_models.uuid_hex_str, editable=False, max_length=32, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
