# Generated by Django 4.2.16 on 2026-03-25 00:13

from django.db import migrations
import host_mgr.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api_cost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicost',
            name='extra',
            field=host_mgr.fields.NullableJSONStringField(blank=True, default=dict, null=True, verbose_name='扩展字段'),
        ),
    ]
