# Generated by Django 4.2.16 on 2026-03-25 09:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_cost', '0003_alter_apicost_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicost',
            name='request_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='请求时间'),
        ),
    ]
