# Generated by Django 4.2.16 on 2026-03-24 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('path', models.CharField(max_length=255, verbose_name='请求路径')),
                ('method', models.CharField(max_length=16, verbose_name='请求方法')),
                ('status_code', models.PositiveIntegerField(verbose_name='响应状态码')),
                ('duration_ms', models.PositiveIntegerField(verbose_name='耗时(毫秒)')),
                ('request_at', models.DateTimeField(auto_now_add=True, verbose_name='请求时间')),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='客户端IP')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='扩展字段')),
            ],
            options={
                'verbose_name': 'API耗时',
                'verbose_name_plural': 'API耗时',
                'db_table': 'api_cost',
                'ordering': ['-request_at'],
                'indexes': [models.Index(fields=['path', 'method'], name='api_cost_path_b2990e_idx'), models.Index(fields=['request_at'], name='api_cost_request_c1d64e_idx')],
            },
        ),
    ]
