# Generated by Django 4.2.16 on 2026-03-25 19:34

from django.db import migrations, models
import django.db.models.deletion
import host_mgr.base_models
import host_mgr.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('idc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.CharField(default=host_mgr.base_models.uuid_hex_str, editable=False, max_length=32, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('extra', host_mgr.fields.NullableJSONStringField(blank=True, default=None, null=True, verbose_name='扩展字段')),
                ('hostname', models.CharField(max_length=128, unique=True, verbose_name='主机名')),
                ('ip', models.GenericIPAddressField(unique=True, verbose_name='IP地址')),
                ('ssh_port', models.PositiveIntegerField(default=22, verbose_name='SSH端口')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('idc', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='hosts', to='idc.idc', verbose_name='所属机房')),
            ],
            options={
                'verbose_name': '主机',
                'verbose_name_plural': '主机',
                'db_table': 'host',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HostPassword',
            fields=[
                ('id', models.CharField(default=host_mgr.base_models.uuid_hex_str, editable=False, max_length=32, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('extra', host_mgr.fields.NullableJSONStringField(blank=True, default=None, null=True, verbose_name='扩展字段')),
                ('encrypted_password', models.TextField(verbose_name='加密后的root密码')),
                ('valid_from', models.DateTimeField(auto_now_add=True, verbose_name='生效时间')),
                ('valid_to', models.DateTimeField(blank=True, null=True, verbose_name='失效时间')),
                ('is_current', models.BooleanField(default=True, verbose_name='是否当前密码')),
                ('host', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='passwords', to='host.host', verbose_name='主机')),
            ],
            options={
                'verbose_name': '主机密码',
                'verbose_name_plural': '主机密码',
                'db_table': 'host_password',
                'ordering': ['-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='HostStatistic',
            fields=[
                ('id', models.CharField(default=host_mgr.base_models.uuid_hex_str, editable=False, max_length=32, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('extra', host_mgr.fields.NullableJSONStringField(blank=True, default=None, null=True, verbose_name='扩展字段')),
                ('stat_date', models.DateTimeField(auto_now=True, verbose_name='统计时间')),
                ('object_id', models.CharField(max_length=32, verbose_name='统计对象ID')),
                ('host_count', models.PositiveIntegerField(default=0, verbose_name='主机数量')),
                ('content_type', models.ForeignKey(db_constraint=False, help_text='城市或机房', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype', verbose_name='统计资源类型')),
            ],
            options={
                'verbose_name': '主机统计',
                'verbose_name_plural': '主机统计',
                'db_table': 'host_statistic',
                'ordering': ['-stat_date', 'content_type_id', 'object_id'],
                'indexes': [models.Index(fields=['stat_date', 'content_type', 'object_id'], name='host_statis_stat_da_2fbacb_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='hoststatistic',
            constraint=models.UniqueConstraint(fields=('stat_date', 'content_type', 'object_id'), name='uniq_host_statistic_date_scope'),
        ),
        migrations.AddIndex(
            model_name='hostpassword',
            index=models.Index(fields=['host', 'is_current'], name='host_passwo_host_id_c09aab_idx'),
        ),
        migrations.AddIndex(
            model_name='hostpassword',
            index=models.Index(fields=['valid_from'], name='host_passwo_valid_f_09b978_idx'),
        ),
    ]
