# Generated by Django 4.2.16 on 2026-03-24 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('idc', '0001_initial'),
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('hostname', models.CharField(max_length=128, unique=True, verbose_name='主机名')),
                ('ip', models.GenericIPAddressField(unique=True, verbose_name='IP地址')),
                ('ssh_port', models.PositiveIntegerField(default=22, verbose_name='SSH端口')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='扩展字段')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('idc', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='hosts', to='idc.idc', verbose_name='所属机房')),
            ],
            options={
                'verbose_name': '主机',
                'verbose_name_plural': '主机',
                'db_table': 'host',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HostStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('stat_date', models.DateField(verbose_name='统计日期')),
                ('host_count', models.PositiveIntegerField(default=0, verbose_name='主机数量')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='扩展字段')),
                ('city', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='host_statistics', to='city.city', verbose_name='城市')),
                ('idc', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='host_statistics', to='idc.idc', verbose_name='机房')),
            ],
            options={
                'verbose_name': '主机统计',
                'verbose_name_plural': '主机统计',
                'db_table': 'host_statistic',
                'ordering': ['-stat_date', 'city_id', 'idc_id'],
                'indexes': [models.Index(fields=['stat_date', 'city', 'idc'], name='host_statis_stat_da_973143_idx')],
                'unique_together': {('stat_date', 'city', 'idc')},
            },
        ),
        migrations.CreateModel(
            name='HostPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('encrypted_password', models.TextField(verbose_name='加密后的root密码')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='变更时间')),
                ('valid_from', models.DateTimeField(auto_now_add=True, verbose_name='生效时间')),
                ('valid_to', models.DateTimeField(blank=True, null=True, verbose_name='失效时间')),
                ('is_current', models.BooleanField(default=True, verbose_name='是否当前密码')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='扩展字段')),
                ('host', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='passwords', to='host.host', verbose_name='主机')),
            ],
            options={
                'verbose_name': '主机密码',
                'verbose_name_plural': '主机密码',
                'db_table': 'host_password',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['host', 'is_current'], name='host_passwo_host_id_c09aab_idx'), models.Index(fields=['changed_at'], name='host_passwo_changed_6937cb_idx')],
            },
        ),
    ]
